Repository AY2223S1-CS2103T-T10-3/tp, pull requests merged in 2022-10, with the labels that each got.

#56 Update Help window for WorkBook
  src/main/java/seedu/workbook/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Story, priority.High

#58 Add internship application stage attribute to internship class
  src/main/java/seedu/workbook/logic/commands/AddCommand.java
  src/main/java/seedu/workbook/logic/commands/EditCommand.java
  src/main/java/seedu/workbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/workbook/logic/parser/CliSyntax.java
  src/main/java/seedu/workbook/logic/parser/EditCommandParser.java
  src/main/java/seedu/workbook/logic/parser/ParserUtil.java
  src/main/java/seedu/workbook/model/internship/Internship.java
  src/main/java/seedu/workbook/model/internship/Stage.java
  src/main/java/seedu/workbook/model/util/SampleDataUtil.java
  src/main/java/seedu/workbook/storage/JsonAdaptedInternship.java
  src/main/java/seedu/workbook/ui/InternshipCard.java
  src/main/resources/view/InternshipListCard.fxml
  src/test/data/JsonSerializableWorkBookTest/duplicateInternshipWorkBook.json
  src/test/data/JsonSerializableWorkBookTest/invalidInternshipWorkBook.json
  src/test/data/JsonSerializableWorkBookTest/typicalInternshipsWorkBook.json
  src/test/data/JsonWorkBookStorageTest/invalidAndValidInternshipWorkBook.json
  src/test/data/JsonWorkBookStorageTest/invalidInternshipWorkBook.json
  src/test/java/seedu/workbook/logic/LogicManagerTest.java
  src/test/java/seedu/workbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/workbook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/workbook/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/workbook/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/workbook/testutil/InternshipBuilder.java
  src/test/java/seedu/workbook/testutil/InternshipUtil.java
  src/test/java/seedu/workbook/testutil/TypicalInternships.java
Labels: type.Story, priority.High

#60 Add Undo Command
  src/main/java/seedu/workbook/logic/commands/AddCommand.java
  src/main/java/seedu/workbook/logic/commands/ClearCommand.java
  src/main/java/seedu/workbook/logic/commands/DeleteCommand.java
  src/main/java/seedu/workbook/logic/commands/EditCommand.java
  src/main/java/seedu/workbook/logic/commands/UndoCommand.java
  src/main/java/seedu/workbook/logic/parser/WorkBookParser.java
  src/main/java/seedu/workbook/model/Model.java
  src/main/java/seedu/workbook/model/ModelManager.java
  src/main/java/seedu/workbook/model/VersionedWorkBook.java
  src/test/java/seedu/workbook/logic/LogicManagerTest.java
  src/test/java/seedu/workbook/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/workbook/logic/commands/AddCommandTest.java
  src/test/java/seedu/workbook/logic/commands/ClearCommandTest.java
  src/test/java/seedu/workbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/workbook/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/workbook/logic/commands/EditCommandTest.java
  src/test/java/seedu/workbook/logic/commands/UndoCommandTest.java
Labels: type.Story, priority.Medium

#64 Delete phone attribute
  src/main/java/seedu/workbook/logic/commands/AddCommand.java
  src/main/java/seedu/workbook/logic/commands/EditCommand.java
  src/main/java/seedu/workbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/workbook/logic/parser/CliSyntax.java
  src/main/java/seedu/workbook/logic/parser/EditCommandParser.java
  src/main/java/seedu/workbook/logic/parser/ParserUtil.java
  src/main/java/seedu/workbook/model/internship/Internship.java
  src/main/java/seedu/workbook/model/internship/Phone.java
  src/main/java/seedu/workbook/model/util/SampleDataUtil.java
  src/main/java/seedu/workbook/storage/JsonAdaptedInternship.java
  src/main/java/seedu/workbook/ui/InternshipCard.java
  src/main/resources/view/InternshipListCard.fxml
  src/test/data/JsonSerializableWorkBookTest/duplicateInternshipWorkBook.json
  src/test/data/JsonSerializableWorkBookTest/invalidInternshipWorkBook.json
  src/test/data/JsonSerializableWorkBookTest/typicalInternshipsWorkBook.json
  src/test/data/JsonWorkBookStorageTest/invalidAndValidInternshipWorkBook.json
  src/test/data/JsonWorkBookStorageTest/invalidInternshipWorkBook.json
  src/test/java/seedu/workbook/logic/LogicManagerTest.java
  src/test/java/seedu/workbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/workbook/logic/commands/EditCommandTest.java
  src/test/java/seedu/workbook/logic/commands/EditInternshipDescriptorTest.java
  src/test/java/seedu/workbook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/workbook/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/workbook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/workbook/model/internship/CompanyContainsKeywordsPredicateTest.java
  src/test/java/seedu/workbook/model/internship/InternshipTest.java
  src/test/java/seedu/workbook/model/internship/PhoneTest.java
  src/test/java/seedu/workbook/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/workbook/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/workbook/testutil/InternshipBuilder.java
  src/test/java/seedu/workbook/testutil/InternshipUtil.java
  src/test/java/seedu/workbook/testutil/TypicalInternships.java
Labels: priority.High, severity.Medium

#66 Add optional email field
  src/main/java/seedu/workbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/workbook/model/internship/Email.java
  src/main/resources/view/InternshipListCard.fxml
  src/test/java/seedu/workbook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/workbook/model/internship/EmailTest.java
Labels: priority.Medium

#69 Change error messages and help window
  src/main/java/seedu/workbook/logic/commands/AddCommand.java
  src/main/java/seedu/workbook/logic/commands/EditCommand.java
  src/main/java/seedu/workbook/model/internship/Internship.java
  src/main/java/seedu/workbook/ui/HelpWindow.java
Labels: priority.High

#71 Fix Documentation Issues
  src/main/java/seedu/workbook/commons/core/index/Index.java
  src/main/java/seedu/workbook/commons/util/AppUtil.java
  src/main/java/seedu/workbook/commons/util/CollectionUtil.java
  src/main/java/seedu/workbook/commons/util/FileUtil.java
  src/main/java/seedu/workbook/logic/Logic.java
  src/main/java/seedu/workbook/logic/commands/AddCommand.java
  src/main/java/seedu/workbook/logic/commands/ClearCommand.java
  src/main/java/seedu/workbook/logic/commands/DeleteCommand.java
  src/main/java/seedu/workbook/logic/commands/EditCommand.java
  src/main/java/seedu/workbook/logic/commands/ExitCommand.java
  src/main/java/seedu/workbook/logic/commands/FindCommand.java
  src/main/java/seedu/workbook/logic/commands/HelpCommand.java
  src/main/java/seedu/workbook/logic/commands/ListCommand.java
  src/main/java/seedu/workbook/logic/commands/UndoCommand.java
  src/main/java/seedu/workbook/model/Model.java
  src/main/java/seedu/workbook/model/ModelManager.java
  src/main/java/seedu/workbook/model/ReadOnlyWorkBook.java
  src/main/java/seedu/workbook/model/VersionedWorkBook.java
  src/main/java/seedu/workbook/model/WorkBook.java
  src/main/java/seedu/workbook/model/internship/Email.java
  src/main/java/seedu/workbook/model/internship/UniqueInternshipList.java
  src/test/java/seedu/workbook/logic/commands/UndoCommandTest.java
Labels: priority.Medium

#72 Add sorting use case to dg
  .gitignore
  docs/DeveloperGuide.md
Labels: priority.Medium

#73 Enable assertions in build.gradle
  build.gradle
Labels: type.Task, priority.Medium

#76 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#75 Add use case for undo command to Developer Guide
  docs/DeveloperGuide.md
Labels: priority.Medium

#78 Add Redo Command
  src/main/java/seedu/workbook/logic/commands/RedoCommand.java
  src/main/java/seedu/workbook/logic/commands/UndoCommand.java
  src/main/java/seedu/workbook/logic/parser/WorkBookParser.java
  src/main/java/seedu/workbook/model/Model.java
  src/main/java/seedu/workbook/model/ModelManager.java
  src/main/java/seedu/workbook/model/VersionedWorkBook.java
  src/test/java/seedu/workbook/logic/commands/AddCommandTest.java
  src/test/java/seedu/workbook/logic/commands/RedoCommandTest.java
Labels: priority.High

#79 Add redo use case and update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High

#77 Add 3 user stories and 1 use case to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#81 Fix naming convention and testing
  src/main/java/seedu/workbook/commons/util/StringUtil.java
  src/main/java/seedu/workbook/model/internship/Company.java
  src/main/java/seedu/workbook/model/internship/Role.java
  src/main/java/seedu/workbook/model/internship/Stage.java
  src/test/java/seedu/workbook/model/internship/DateTimeTest.java
  src/test/java/seedu/workbook/model/internship/InternshipTest.java
  src/test/java/seedu/workbook/model/internship/RoleTest.java
  src/test/java/seedu/workbook/model/internship/StageTest.java
Labels: priority.High

#83 Add sorting by date
  .gitignore
  src/main/java/seedu/workbook/logic/commands/EditCommand.java
  src/main/java/seedu/workbook/model/ModelManager.java
  src/main/java/seedu/workbook/model/internship/DateTime.java
  src/main/java/seedu/workbook/model/internship/InternshipComparator.java
  src/main/java/seedu/workbook/model/internship/UniqueInternshipList.java
  src/main/java/seedu/workbook/model/util/SampleDataUtil.java
  src/test/java/seedu/workbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/workbook/logic/commands/EditCommandTest.java
  src/test/java/seedu/workbook/logic/commands/FindCommandTest.java
Labels: priority.High

#86 Enhance stage feature
  src/main/java/seedu/workbook/logic/commands/AddCommand.java
  src/main/java/seedu/workbook/model/Model.java
  src/main/java/seedu/workbook/model/internship/Internship.java
  src/main/java/seedu/workbook/model/internship/Stage.java
  src/main/java/seedu/workbook/model/internship/util/StageUtil.java
  src/test/java/seedu/workbook/testutil/InternshipBuilder.java
Labels: type.Bug, type.Task, priority.Medium

#87 Add filter functionality for role and stage
  src/main/java/seedu/workbook/logic/commands/FindCommand.java
  src/main/java/seedu/workbook/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/workbook/logic/parser/FindCommandParser.java
  src/main/java/seedu/workbook/model/internship/RoleContainsKeywordsPredicate.java
  src/main/java/seedu/workbook/model/internship/StageContainsKeywordsPredicate.java
  src/test/java/seedu/workbook/logic/commands/FindCommandTest.java
  src/test/java/seedu/workbook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/workbook/logic/parser/WorkBookParserTest.java
  src/test/java/seedu/workbook/model/internship/CompanyContainsKeywordsPredicateTest.java
  src/test/java/seedu/workbook/model/internship/RoleContainsKeywordPredicateTest.java
  src/test/java/seedu/workbook/model/internship/StageContainsKeywordsPredicateTest.java
Labels: priority.Medium

#88 Add tips window functionality for stages with specific tips
  src/main/java/seedu/workbook/model/internship/Stage.java
  src/main/java/seedu/workbook/model/internship/util/StageUtil.java
  src/main/java/seedu/workbook/ui/InternshipCard.java
  src/main/java/seedu/workbook/ui/TipsWindow.java
  src/main/resources/images/lightbulb.png
  src/main/resources/view/InternshipListCard.fxml
  src/main/resources/view/TipsWindow.css
  src/main/resources/view/TipsWindow.fxml
Labels: type.Bug, type.Story, priority.High

#89 Add language tags
  src/main/java/seedu/workbook/logic/commands/AddCommand.java
  src/main/java/seedu/workbook/logic/commands/EditCommand.java
  src/main/java/seedu/workbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/workbook/logic/parser/CliSyntax.java
  src/main/java/seedu/workbook/logic/parser/EditCommandParser.java
  src/main/java/seedu/workbook/model/internship/Internship.java
  src/main/java/seedu/workbook/model/util/SampleDataUtil.java
  src/main/java/seedu/workbook/storage/JsonAdaptedInternship.java
  src/main/java/seedu/workbook/ui/InternshipCard.java
  src/main/java/seedu/workbook/ui/LanguageTagLabel.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableWorkBookTest/typicalInternshipsWorkBook.json
  src/test/java/seedu/workbook/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/workbook/testutil/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/workbook/testutil/InternshipBuilder.java
  src/test/java/seedu/workbook/testutil/InternshipUtil.java
  src/test/java/seedu/workbook/testutil/TypicalInternships.java
Labels: priority.Medium

#93 Refine responsive UI
  src/main/java/seedu/workbook/ui/InternshipListPanel.java
  src/main/java/seedu/workbook/ui/MainWindow.java
  src/main/java/seedu/workbook/ui/WideInternshipListPanel.java
Labels: priority.High

#94 Add missing commands to help window
  src/main/java/seedu/workbook/logic/commands/AddCommand.java
  src/main/java/seedu/workbook/logic/commands/FindCommand.java
  src/main/java/seedu/workbook/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High

#99 Update UG with undo and redo features
  docs/UserGuide.md
Labels: type.Task, priority.High

#96 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#100 Update user guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.High

#144 Fix ug bugs
  docs/UserGuide.md
  src/main/java/seedu/workbook/logic/commands/AddCommand.java
  src/main/java/seedu/workbook/logic/parser/ParserUtil.java
  src/main/java/seedu/workbook/model/tag/Tag.java
  src/test/java/seedu/workbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/workbook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/workbook/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/workbook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/workbook/storage/JsonAdaptedInternshipTest.java
Labels: priority.Medium

#145 Update UG issues
  docs/UserGuide.md
  docs/images/SortExample.png
  src/main/java/seedu/workbook/model/internship/DateTime.java
  src/main/java/seedu/workbook/ui/HelpWindow.java
Labels: type.Bug, type.Task, priority.High

#146 Fix TOC for UG
  docs/UserGuide.md
Labels: type.Bug
