Repository AY2223S1-CS2103T-T10-3/tp, pull requests merged in 2022-11, with the labels that each got.

#151 Fix numbering for TOC
  docs/_config.yml
  docs/_sass/minima/_layout.scss
Labels: type.Bug, priority.High

#153 UG updates to Introduction and Getting Started
  docs/UserGuide.md
  docs/images/AnnotatedUi.png
  docs/images/SortExample.png
Labels: priority.High

#155 Update PPP
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState4.png
  docs/team/tienyu2000.md
Labels: type.Task, priority.High

#158 Update PPP
  docs/team/rylzxc.md
Labels: type.Task, priority.High

#159 Update PPP
  docs/team/adeearyaa.md
Labels: priority.High

#160 Fix bugs
  docs/UserGuide.md
  src/main/java/seedu/workbook/model/internship/Stage.java
Labels: priority.Medium

#154 Update UG with redo and undo features
  docs/UserGuide.md
  docs/images/AfterDelete.png
  docs/images/AfterEdit.png
  docs/images/AfterRedoStack.png
  docs/images/AfterUndo1.png
  docs/images/AfterUndo2.png
  docs/images/AfterUndoStack.png
  docs/images/BeforeEdit.png
  docs/images/BeforeRedoStack.png
  docs/images/BeforeUndoStack.png
  docs/images/RedoAfterClear.png
  docs/images/RedoAfterEdit.png
  docs/images/RedoAfterRedo.png
  docs/images/RedoAfterUndo1.png
  docs/images/RedoAfterUndo2.png
  docs/images/RedoFailure.png
  docs/images/UndoFailure.png
Labels: type.Task, priority.Medium

#164 Add Images UG
  docs/UserGuide.md
  docs/images/AfterFindRole.png
  docs/images/BeforeFindRole.png
Labels: priority.Medium

#165 Improve UG for `add`
  docs/UserGuide.md
  docs/images/AddCommandResult.png
  docs/images/EditCommandInput.png
  docs/images/EditCommandResult.png
  docs/images/Ui2.png
  docs/images/UiNarrow.png
Labels: priority.High

#166 Fix repeatable UI bugs
  src/main/java/seedu/workbook/ui/InternshipCard.java
  src/main/java/seedu/workbook/ui/TipCard.java
  src/main/java/seedu/workbook/ui/TipsPanel.java
  src/main/java/seedu/workbook/ui/TipsWindow.java
  src/main/java/seedu/workbook/ui/WideInternshipListPanel.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/InternshipListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NarrowInternshipListCard.fxml
  src/main/resources/view/TipCard.fxml
  src/main/resources/view/Tips.css
  src/main/resources/view/TipsPanel.fxml
  src/main/resources/view/TipsWindow.css
  src/main/resources/view/TipsWindow.fxml
  src/main/resources/view/WideInternshipListPanel.fxml
Labels: type.Bug, priority.High

#168 Update testcases
  src/main/java/seedu/workbook/logic/parser/ParserUtil.java
  src/main/java/seedu/workbook/model/tag/Tag.java
  src/test/java/seedu/workbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/workbook/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/workbook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/workbook/logic/parser/WorkBookParserTest.java
  src/test/java/seedu/workbook/model/internship/InternshipTest.java
  src/test/java/seedu/workbook/model/tag/TagTest.java
Labels: priority.Medium

#169 Add sections on Responsive UI and Tips to DG
  docs/DeveloperGuide.md
Labels: priority.High

#177 Add Help window section to DG
  docs/DeveloperGuide.md
Labels: priority.High

#170 Fix `edit` section in UG
  docs/UserGuide.md
  docs/images/EditCommandInput.png
  docs/images/EditCommandResult.png
Labels: type.Bug, priority.High

#179 Add find command to DG
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandDiagram.puml
  docs/images/FindCommandDiagram.png
Labels: priority.High

#175 Improve code quality for Help Window
  src/main/java/seedu/workbook/ui/HelpCard.java
  src/main/java/seedu/workbook/ui/HelpWindow.java
  src/main/java/seedu/workbook/ui/UrlCard.java
  src/main/java/seedu/workbook/ui/util/HelpUtil.java
  src/main/resources/view/HelpCard.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/UrlCard.fxml
Labels: type.Misc

#184 Fix undo and redo in UG
  docs/UserGuide.md
  docs/images/AfterDelete.png
  docs/images/AfterEdit.png
  docs/images/AfterUndo1.png
  docs/images/AfterUndo2.png
  docs/images/BeforeEdit.png
  docs/images/RedoAfterClear.png
  docs/images/RedoAfterEdit.png
  docs/images/RedoAfterRedo.png
  docs/images/RedoAfterUndo1.png
  docs/images/RedoAfterUndo2.png
  docs/images/RedoFailure.png
  docs/images/UndoFailure.png
Labels: priority.High

#185 Update acknowledgements
  README.md
  docs/DeveloperGuide.md
  docs/index.md
Labels: type.Task, priority.High

#187 Improve code quality
  README.md
  docs/DeveloperGuide.md
  docs/index.md
  src/main/java/seedu/workbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/workbook/logic/parser/EditCommandParser.java
  src/main/java/seedu/workbook/logic/parser/ParserUtil.java
  src/main/java/seedu/workbook/logic/parser/util/CheckedFunction.java
  src/main/java/seedu/workbook/model/internship/DateTime.java
  src/main/java/seedu/workbook/storage/JsonAdaptedInternship.java
  src/test/java/seedu/workbook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/workbook/model/internship/DateTimeTest.java
Labels: priority.High
