Repository AY2223S1-CS2103T-T10-3/tp, pull requests merged in 2022-09, with the labels that each got.

#12 Add skeletal PPP
  docs/team/jacobkwan.md
Labels: type.documentation, priority.medium

#8 Update AboutUs.md
  docs/AboutUs.md
  docs/images/jacobkwan.png
Labels: type.documentation, priority.medium

#14 Update About Us page to use real name
  docs/AboutUs.md
Labels: bug, type.documentation, priority.medium

#26 Update docs
  README.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.documentation, priority.high

#34 Add .ruby-version to .gitignore
  .gitignore
Labels: misc

#35 Add a simple UI mockup for WorkBook
  docs/images/Ui.png
Labels: type.documentation, priority.high

#7 Update AboutUs and PPP
  docs/AboutUs.md
  docs/images/tienyu2000.png
  docs/team/tienyu2000.md
Labels: type.documentation, priority.high

#37 Fix Table of Contents for User Guide
  docs/UserGuide.md
Labels: bug

#38 Update User Guide to explain usage of Delete function
  docs/UserGuide.md
Labels: type.documentation, priority.high

#40 Update User Guide to explain usage of Add function
  docs/UserGuide.md
Labels: type.documentation, priority.high

#41 Add NFRs and basic Glossary to Developer Guide
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#39 Update the User Guide with the Clear command
  docs/UserGuide.md
Labels: type.documentation, priority.high

#43 Update user guide
  docs/UserGuide.md
Labels: type.documentation, priority.high
